name: Installing Python

on: [push]

jobs:
  build:
    runs-on: '${{ martix.os }}'
    strategy:
       martix:
         os:
          - ubuntu-latest
          - macos-12
          - windows-latest
         py-version:
            - 3.7
            - 3.8
            - 3.9
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '${{ martix.py-version }}'
